### login
### username : librarian / student
### password : librarian / student
POST http://localhost:8000/api-auth

{
"username": "librarian",
"password": "librarian"
}


### Get list book endpoint
### query params title for search by `title` and `author` to search by author
GET http://localhost:8000/library/books



### Borrow book endpoint
### payload user id and list id of book
### should logged in as librarian
POST http://localhost:8000/library/borrow
Authorization: Bearer <token>


{
"user_id": 2,
"books": [1,2]
}


### renew book endpoint
### payload user id and list id of book to renew
### should logged in as librarian
POST http://localhost:8000/library/renew
Authorization: Bearer <token>


{
"user_id": 2,
"books": [1,2]
}


### return book endpoint
### payload user id and list id of book to return books
### should logged in as librarian
POST http://localhost:8000/library/return
Authorization: Bearer <token>


{
"user_id": 2,
"books": [1,2]
}



### list user endpoint
### should logged in as librarian
GET http://localhost:8000/library/student-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzNDEyMTQxLCJpYXQiOjE2OTMzMjU3NDEsImp0aSI6IjI1ZDhhM2Q5MjMwMDQ3ZWJiOWExODUyZjE5NTdjN2I0IiwidXNlcl9pZCI6MX0.BQdNcs1ILFyHpofXkBdeFjV8SH7Strw2FLXBzk6_B8w


### get list borrow book by student side
### should be logged in by student account
GET http://localhost:8000/library/student/borrow-list
Authorization: Bearer <token>




